

UsedDatasetConfig:
  train_dataset_config:
    static_audio_feature_manifest_or_list: "/data/lipsync/xgyang/E2EGeneration/V1/cache_dir/lumi_hubert_60_train.txt"
    ctrl_manifest_or_list: "/data/lipsync/xgyang/E2EGeneration/V1/cache_dir/lumi_normalized_extracted_ctrl_train.txt"
    feature_rate: 60
    label_rate: 60
    max_keep_feature_size:
    min_keep_feature_size:
  validate_dataset_config:
    static_audio_feature_manifest_or_list: "/data/lipsync/xgyang/E2EGeneration/V1/cache_dir/lumi_hubert_60_validate.txt"
    ctrl_manifest_or_list: "/data/lipsync/xgyang/E2EGeneration/V1/cache_dir/lumi_normalized_extracted_ctrl_validate.txt"
    feature_rate: 60
    label_rate: 60
    max_keep_feature_size:
    min_keep_feature_size:

TrainingConfig:
  # weight_decay: 0.
  gradient_clip_val:
  devices: [0]
  loss_config:
    wing_loss_config:
      omega: 10
  checkpoint_config:
    save_checkpoint: True
    checkpoint_dir: "/data/lipsync/xgyang/E2EGeneration/V1/checkpoint_dir/model_1/v3"
    checkpoint_sub_name: "{epoch}-{step}-{validate_loss:.4f}"
    monitor: "validate_loss"
    save_last: True
    save_top_k: 4
    save_weights_only: False
    mode: "min"
    every_n_epochs: 1
    every_n_train_steps: 
    save_on_train_epoch_end: False
  phn_embedding_config:
    add_phn: True
    train_phn_manifest_path: /data/lipsync/xgyang/E2EGeneration/V1/cache_dir/lumi_phn_60_train.txt
    validate_phn_manifest_path: /data/lipsync/xgyang/E2EGeneration/V1/cache_dir/lumi_phn_60_validate.txt
    phn_num: 63
    phn_padding_idx: 0
    phn_directly_pad: True
    phn_flatten_pad: True
    
Model1Config:
  pre_lnorm: True
