

UsedDatasetConfig:
  train_dataset_config:
    static_audio_feature_manifest_or_list: "/data/lipsync/xgyang/E2EGeneration/V1/cache_dir/after_filter_1/lumi_hubert_60_train_repeat.txt"
    ctrl_manifest_or_list: "/data/lipsync/xgyang/E2EGeneration/V1/cache_dir/after_filter_1/lumi_normalized_extracted_ctrl_train_repeat.txt"
    feature_rate: 60
    label_rate: 60
    max_keep_feature_size:
    min_keep_feature_size:
  validate_dataset_config:
    static_audio_feature_manifest_or_list: "/data/lipsync/xgyang/E2EGeneration/V1/cache_dir/lumi_hubert_60_validate_ori.txt"
    ctrl_manifest_or_list: "/data/lipsync/xgyang/E2EGeneration/V1/cache_dir/lumi_normalized_extracted_ctrl_validate_ori.txt"
    feature_rate: 60
    label_rate: 60
    max_keep_feature_size:
    min_keep_feature_size:

TrainingConfig:
  # weight_decay: 0.
  gradient_clip_val:
  n_epochs: 100
  devices: [4]
  check_val_every_n_epoch: 
  val_check_interval: 750
  checkpoint_config:
    save_checkpoint: True
    checkpoint_dir: "/data/lipsync/xgyang/E2EGeneration/V1/checkpoint_dir/model_1/v5_all"
    checkpoint_sub_name: "{epoch}-{step}-{validate_loss:.4f}"
    monitor: "validate_loss"
    save_last: True
    save_top_k: 2
    save_weights_only: False
    mode: "min"
    every_n_epochs: 1
    every_n_train_steps: 
    save_on_train_epoch_end: False
  phn_embedding_config:
    add_phn: True
    train_phn_manifest_path: /data/lipsync/xgyang/E2EGeneration/V1/cache_dir/after_filter_1/lumi_phn_60_train_repeat.txt
    validate_phn_manifest_path: /data/lipsync/xgyang/E2EGeneration/V1/cache_dir/lumi_phn_60_validate.txt
    phn_num: 63
    phn_padding_idx: 0
    phn_directly_pad: True
    phn_flatten_pad: True
    
Model1Config:
  pre_lnorm: True

  hidden_size: 768
  encoder_layer_num: 6
  encoder_head_num: 6
  encoder_head_dim: 128
  encoder_conv1d_filter_size: 3072
  encoder_conv1d_kernel_size: 3
  encoder_dropout_p: 0.1
  encoder_dropatt_p: 0.1
  encoder_dropemb_p: 0.0

  mouth_decoder_layer_num: 5
  mouth_decoder_head_num: 6
  mouth_decoder_head_dim: 128
  mouth_decoder_conv1d_filter_size: 3072
  mouth_decoder_conv1d_kernel_size: 3
  mouth_decoder_dropout_p: 0.1
  mouth_decoder_dropatt_p: 0.1
  mouth_decoder_dropemb_p: 0.0
