

UsedDatasetConfig:
  train_dataset_config:
    static_audio_feature_manifest_or_list: "/data/lipsync/xgyang/E2EGeneration/V1/cache_dir/lumi05_feature_huebrt_60_train.txt"
    ctrl_manifest_or_list: "/data/lipsync/xgyang/E2EGeneration/V1/cache_dir/lumi05_ctrl_train.txt"
    feature_rate: 60
    label_rate: 60
    max_keep_feature_size:
    min_keep_feature_size:

